export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_YEAR_DATA = 'FETCH_YEAR_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const SET_BARCHART_DATA = 'SET_BARCHART_DATA';
